language: c
os: linux
dist: bionic

addons:
    apt:
        packages:
            googletest

script: ./build_for_tests.sh && ./run_tests.sh
notifications:
    email:
        # c-dev@apache.axis.org doesn't work here because it's not an address registered on GitHub.
        - billblough@apache.org
