#test_print Attachment1.wsdl
#test_print AttachmentService.wsdl
./test_print AxisBench.wsdl
./test_print BasicAllTest.wsdl
./test_print BasicChoice.wsdl
./test_print CalculatorDoc.wsdl
./test_print Calculator.wsdl
./test_print Choice.wsdl
./test_print CombinedAllTest.wsdl
./test_print CombinedChoice.wsdl
./test_print ComplexLists.wsdl
./test_print ComplexTypeAll.wsdl
#./test_print DataHandlerService.wsdl
./test_print Enumeration.wsdl
./test_print ExceptionTest.wsdl
./test_print ExtensibilityQuery.wsdl
./test_print FaultMappingDoc.wsdl
./test_print FaultMapping.wsdl
./test_print FourLevelTestDoc.wsdl
./test_print InOut.wsdl
#./test_print inquire_v2.wsdl
./test_print InteropTestRound1Doc.wsdl
./test_print InteropTestRound1.wsdl
./test_print LargeReturningString.wsdl
./test_print LimitedAllTest.wsdl
./test_print ManyTypeRefRoot.wsdl
./test_print MathOpsDoc.wsdl
./test_print MathOps.wsdl
./test_print MinOccurTest.wsdl
./test_print MultiOut.wsdl
./test_print NestedArrays.wsdl
./test_print NestedComplex.wsdl
./test_print NillableArrays.wsdl
./test_print nillableComplexType.wsdl
./test_print OtherFaultException.wsdl
#./test_print PlainTextAttachment.wsdl
./test_print PrimitiveAndArray.wsdl
./test_print RecurseTypes.wsdl
./test_print RPCAllTest.wsdl
./test_print RpcHttpHeaderTest1.wsdl
./test_print RpcHttpHeaderTest2.wsdl
./test_print RpcHttpHeaderTest3.wsdl
./test_print RpcHttpHeaderTest4.wsdl
./test_print RpcHttpHeaderTest5.wsdl
./test_print RpcHttpHeaderTest7.wsdl
./test_print RpcHttpHeaderTest8.wsdl
./test_print RpcSoapHeaderTest1.wsdl
./test_print RpcSoapHeaderTest2.wsdl
./test_print RpcSoapHeaderTest3.wsdl
./test_print RpcSoapHeaderTest4.wsdl
./test_print RpcSoapHeaderTest6.wsdl
./test_print RpcSoapHeaderTest8.wsdl
./test_print RpcSoapHeaderTest9.wsdl
./test_print RpcSoapHeaderTest10.wsdl
./test_print SimpleArrayDoc.wsdl
./test_print SimpleArrays.wsdl
