TESTS =
lib_LTLIBRARIES = libaxis2_xml_schema.la
libaxis2_xml_schema_la_SOURCES = \
								 xml_schema_identity_constraint.c

INCLUDES = -I$(top_builddir)/include \
            -I$(top_builddir)/modules/util \
            -I$(top_builddir)/modules/platforms
